### PR TITLE
Possibility to define HTTP status code on mapping

### PR DESCRIPTION
**Pull request by Murasj**

### CODE REVIEW

**Comment by kulasekp** [comment]
Maybe we could provide select with all available values instead of textarea?

**Comment by Murasj** [comment]
Select with all http status codes contains around 60 values and angular probably can't render more than 10-15 values in select. It throws errors from js.

**Comment by kulasekp** [comment]
https://material.angularjs.org/latest/demo/select

Please take a look at Basic Usage. Works fine so maybe the issue is on our side. Could you investigate?

**Comment by Murasj** [comment]
Done. In org.springframework.http.HttpStatus were duplicated values and this caused an issue.

**Comment by kulasekp** [comment]
Could we improve it a bit?

- Status -> Response status 
- Response status and Status should not be in the same line
- dropdown should contains both code and its description (i.e. 200 OK, 201 Created, etc)

Plus there is something wrong when trying to edit just created mapping:
1. Add new mapping
2. Save it
3. Click on edit
2016-08-17 19:34:02.367  WARN 3565 --- [nio-8081-exec-9] `.w.s.m.s.DefaultHandlerExceptionResolver : Failed to bind request element: org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type [java.lang.String] to required type [long]; nested exception is java.lang.NumberFormatException: For input string: "undefined"`

**Comment by kulasekp** [comment]
Please take a look at SonarQube too: https://sonarqube.com/component_issues?id=pl.hycom.mokka%3Amokka-parent#createdAfter=2016-08-15T01%3A00%3A00%2B0200|resolved=false

**Comment by kulasekp** [comment]
Left to do:
- Response status and Status should not be in the same line

Unless you disagree :)

**Pull request merged**
